services:
  - type: web
    name: cogniticharts
    env: docker
    plan: free
    region: oregon 
    branch: main
    repo: https://github.com/UtkarshGupta7799/CognitiCharts
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8501
